import os
master,slave = os.openpty()
from ctypes import *
libc = cdll.LoadLibrary('libc.so.6')
#libc.grantpt(master)
#libc.unlockpt(master)
print(os.ttyname(slave))
data = os.read(master, 4096)
print(data)
os.write(master, b'p 1')
data = os.read(master, 16)
print(data)
data = os.read(master, 16)
print(data)
os.close(master)
os.close(slave)
